services:
  database:
    image: postgres:15-alpine
    container_name: books_inventory_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
