services:
  database:
    image: postgres:15-alpine
    container_name: books_inventory_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "books_inventory"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

  # Jaeger
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI

  # OpenTelemetry Collector
  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.125.0
    container_name: otel_collector
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./tools/telemetry/otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317" # expose this on the host if you run the web app locally
    depends_on:
      jaeger:
        condition: service_started

volumes:
  postgres-data:
  redis-data:
